spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    password:
    url: jdbc:mysql://127.0.0.1:3306/taco_app
    username: root
  jpa:
    hibernate:
      ddl_auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
      show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
  mvc:
    log-request-details: true
  thymeleaf:
    cache: false
    enable-spring-el-compiler: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    servlet:
      content-type: text/html;charset=UTF-8
    suffix: .html
  activemq:
    broker-url: tcp://localhost:61616
logging:
  level:
    org:
      springframework:
        security: DEBUG
taco :
  orders:
    page-size: 10